trigger:
  branches:
    include:
      - master
  paths:
    include: 
      - '/azure/*'
      - '/src/*'
      - '/test/*'

pr:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Import the shared variable group that holds common configurations that apply to all environments
  - group: shared

  # I add these variables to always have more debug output without having to tick a box at the start of each run. This avoids me having to re-run a failed deployment to get more output
  - name: system.debug
    value: true
  - name: agent.diagnostic
    value: true

stages:

# Stage that builds the WebApp and publishes the deployable artifacts
- template: ./templates/build-stage.yml

# The following stages deploy infrastrcuture and the webapp for specific environment
#
# To support a new environment
#   1. clone (copy-paste) one of the existing stages
#   2. rename the environmentName parameter (must be unique in the environment list)
#   3. set the dependent stage name
#   4. in azure devops, create a variable group with the exact same name as the environmentName
# 
- template: ./templates/deploy-stage.yml
  parameters:
    projectName: $(projectName)
    resourceGroupPrefix: $(resourceGroupPrefix)
    azureSubscriptionName: $(azureSubscriptionName)
    azureSubscriptionId: $(azureSubscriptionId)
    environmentName: dev
    dependsOnStageName: Build

# - template: ./templates/deploy-stage.yml
#   parameters:
#     projectName: $(projectName)
#     resourceGroupPrefix: $(resourceGroupPrefix)
#     azureSubscriptionName: $(azureSubscriptionName)
#     azureSubscriptionId: $(azureSubscriptionId)
#     environmentName: staging
#     dependsOnStageName: dev

# - template: ./templates/deploy-stage.yml
#   parameters:
#     projectName: $(projectName)
#     resourceGroupPrefix: $(resourceGroupPrefix)
#     azureSubscriptionName: $(azureSubscriptionName)
#     azureSubscriptionId: $(azureSubscriptionId)
#     environmentName: prod
#     dependsOnStageName: staging
