parameters:
  buildConfiguration: Release
  buildId: unknown

stages:
- stage: Build
  displayName: Build WebApp and Publish artifacts
  jobs:
  - job: BuildAndPublishWebApp
    displayName: Build and Test, then publish artifacts
    steps:
    - template: build-steps.yml
      parameters:
        buildConfiguration: ${{parameters.buildConfiguration}}
        buildId: ${{parameters.buildId}}
