parameters:
  azureSubscriptionName: 
  azureSubscriptionId: 
  projectName:
  resourceGroupPrefix:
  environmentName:
  dependsOnStageName: Build
  # australiasoutheast or australiaeast
  location: 'australiaeast'

stages:
- stage: ${{parameters.environmentName}}
  displayName: Deploy ${{parameters.environmentName}}
  dependsOn: ${{parameters.dependsOnStageName}}
  # prevent deployment on PullRequest builds
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - deployment: Deploy
    displayName: Deploy Azure Infra & WebApp
    environment: ${{parameters.environmentName}}

    variables:
    # e.g. DEV, TRAINING, STAGING, PROD
    - group: '${{parameters.environmentName}}'

    # IMPORTANT: This is the naming convention for Azure Resource Groups (<ProjecSpecificPrefix>-<environmentName>)
    - name: resourceGroupName
      value: '${{parameters.resourceGroupPrefix}}-${{lower(parameters.environmentName)}}'

    strategy:
      runOnce:
        deploy:
          steps:

          # Step 1 - Deploy Infra
          - template: deploy-infra-steps.yml
            parameters:
              projectName: ${{parameters.projectName}}
              environmentName: ${{parameters.environmentName}} 
              azureServiceConnection:  ${{parameters.azureSubscriptionName}} 
              azureSubscriptionId: ${{parameters.azureSubscriptionId}}
              resourceGroupName: $(resourceGroupName)
              location: ${{parameters.location}}
              artifactPath: $(Pipeline.Workspace)/infra

          # Step 2 - Deploy WebApp
          - template: deploy-webapp-steps.yml
            parameters:
              azureServiceConnection:  ${{parameters.azureSubscriptionName}} 
              artifactPath: $(Pipeline.Workspace)/webapp
              # NOTE: We are referencing the BICEPOUTPUT_WEBAPPNAME output variable from the DeployInfra task in the deploy-infra-steps.yml template
              webappName: $(DeployInfra.BICEPOUTPUT_WEBAPPNAME)
